In [111]:
import pandas as pd

viewed_posts = pd.read_csv("viewed_posts.csv")
print(viewed_posts.isnull().sum())  # Check for missing values
print(viewed_posts.head())

Post ID      0
User ID      0
Viewed At    0
dtype: int64
   Post ID  User ID            Viewed At
0      631      114  2024-01-10 07:20:55
1      626      114  2024-01-10 07:21:18
2      571      114  2024-01-10 07:22:02
3      558      116  2024-01-10 12:33:47
4      551      116  2024-01-10 12:33:55

In [112]:
summary_posts = pd.read_csv("summary_posts.csv")
# print(summary_posts.isnull().sum())  # Check for missing values
print(summary_posts.columns)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19128\2197829446.py:1: DtypeWarning: Columns (1,2,3,4,6,12,13,15,20,26,28,29,30,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,115,116,117,118,119,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,156,157,158,159,160,161,162,163,164,167,168,169,170,171,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,247,248,249,250,251,252,253,254,255,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,285,286,287,288,290,291,292,293,294,295,296,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,337,339,341,342,343,344,345,346,347,348,350,351,352,354,355,356,358,359,360,361,362,363,364,365,366,368,369,370,371,372,373,374,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,455,456,459,460,461,462,465,466,468,469,470,472,475,476,477,478,479,480,482,483,484,485,486,487,488,489,490,491,492,494,495,496,497,498,499,500,501,502,503,504,506,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,537,539,541,542,543,544,545,546,547,548,549,550,551,552,553,554,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,574,575,576,579,580,581,582,583,584,585,586,587,588,589,590,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,621,622,623,624,625,626,629,630,631,632,633,634,635,636,637,638,640,641,642,643,644,645,647,648,649,650,651,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,674,675,676,677,678,679,680,681,682,683,684,685,686,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,870,871,872,873,874,877,879,880,881,884,885,886,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,913,914,915,916,917,918,919,920,923,925,926,927,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,969,970,971,973,974,975,976,979,980,981,982,983,984,985,986,987,988,989,992,993,994,996,997,998,999,1000,1001,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1076,1077,1079,1080,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1107,1108,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1123,1125,1126,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1150,1152,1154,1157,1158,1160,1161,1162,1163,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1197,1198,1199,1201,1203,1204,1206,1207,1209,1210,1211,1212,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1225,1226,1228,1230,1231,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1312,1313,1314,1315,1316,1317,1318,1320,1321,1322,1323,1324,1325,1326,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1369,1371,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1386,1388,1389,1390,1391,1392,1393,1394,1395,1396,1398,1399,1400,1402,1404,1405,1406,1407,1409,1410,1411,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1438,1439,1440,1441,1442,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1457,1458,1459,1460,1461,1462,1465,1466,1467,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1548,1549,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1594,1595,1597,1598,1599,1600,1601,1602,1603,1604,1606,1607,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1622,1623,1624,1627,1628,1629,1630,1631,1633,1634,1635,1636,1637,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1716,1717,1718,1719,1721,1722,1724,1725,1726,1727,1728,1729,1730,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1786,1788,1789,1790,1793,1795,1796,1797,1798,1799,1800,1801,1802,1805,1806,1807,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1860,1861,1862,1863,1864,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1880,1881,1882,1883,1884,1885,1886) have mixed types. Specify dtype option on import or set low_memory=False.
  summary_posts = pd.read_csv("summary_posts.csv")

Index(['average_rating', 'baseToken_address', 'baseToken_image_url',
       'baseToken_name', 'baseToken_symbol', 'bookmarked', 'category',
       'category_count', 'category_description', 'category_id',
       ...
       'rating_count', 'share_count', 'slug', 'thumbnail_url', 'title',
       'upvote_count', 'upvoted', 'username', 'video_link', 'view_count'],
      dtype='object', length=1897)

In [113]:
print(len(summary_posts))

1136

In [ ]:
threshold = 0.7

non_missing_percentage = summary_posts.notnull().mean()

columns_to_keep = non_missing_percentage[non_missing_percentage > threshold].index


filtered_df = summary_posts[columns_to_keep]


print("Original DataFrame:")
print(summary_posts.columns)

print("\nFiltered DataFrame:")
print(filtered_df.columns)

Original DataFrame:
Index(['average_rating', 'baseToken_address', 'baseToken_image_url',
       'baseToken_name', 'baseToken_symbol', 'bookmarked', 'category',
       'category_count', 'category_description', 'category_id',
       ...
       'rating_count', 'share_count', 'slug', 'thumbnail_url', 'title',
       'upvote_count', 'upvoted', 'username', 'video_link', 'view_count'],
      dtype='object', length=1897)

Filtered DataFrame:
Index(['average_rating', 'bookmarked', 'category_count',
       'category_description', 'category_id', 'category_image_url',
       'category_name', 'comment_count', 'created_at', 'exit_count',
       'first_name', 'following', 'id', 'identifier', 'is_locked', 'last_name',
       'picture_url', 'post_summary_description',
       'post_summary_estimated_duration', 'post_summary_genre',
       'post_summary_is_face_exist', 'post_summary_keywords',
       'post_summary_main_person_details_gender',
       'post_summary_main_person_details_name',
       'post_summary_no_of_person_in_video',
       'post_summary_other_person_details', 'rating_count', 'share_count',
       'slug', 'thumbnail_url', 'title', 'upvote_count', 'upvoted', 'username',
       'video_link', 'view_count'],
      dtype='object')

In [115]:
pd.set_option('display.max_columns', None)


filtered_df.head()

,average_rating,bookmarked,category_count,category_description,category_id,category_image_url,category_name,comment_count,created_at,exit_count,first_name,following,id,identifier,is_locked,last_name,picture_url,post_summary_description,post_summary_estimated_duration,post_summary_genre,post_summary_is_face_exist,post_summary_keywords,post_summary_main_person_details_gender,post_summary_main_person_details_name,post_summary_no_of_person_in_video,post_summary_other_person_details,rating_count,share_count,slug,thumbnail_url,title,upvote_count,upvoted,username,video_link,view_count
0,36,False,535.0,All the best vibes!,2.0,https://assets.socialverseapp.com/categories/a...,Vible,0,1698088807000,0,Michael,True,11,OSsJAMz,False,Dadzie,https://assets.socialverseapp.com/profile/afro...,The video unfolds as a dynamic exploration of ...,"exact timing not provided, likely matches audi...",Educational/Inspirational,True,"[{""keyword"": ""flow state"", ""weight"": 10}, {""ke...",male,unknown male speaker,1.0,NaN,7,8,recipe-for-a-flow-state,https://video-cdn.socialverseapp.com/michael_9...,Recipe for a flow state,45,True,afrobeezy,https://video-cdn.socialverseapp.com/michael_9...,64
1,0,False,535.0,All the best vibes!,2.0,https://assets.socialverseapp.com/categories/a...,Vible,0,1698096725000,0,Michael,True,12,iGqBOIW,False,Dadzie,https://assets.socialverseapp.com/profile/afro...,The video is structured as an emotional and in...,Approximately 3 minutes,Animation/Emotional Narrative,True,"[{""keyword"": ""individuality"", ""weight"": 10}, {...",Not specified,Protagonist,3.0,NaN,0,0,why-fit-in,https://video-cdn.socialverseapp.com/michael_5...,Why fit in..?,42,False,afrobeezy,https://video-cdn.socialverseapp.com/michael_5...,54
2,8,False,535.0,All the best vibes!,2.0,https://assets.socialverseapp.com/categories/a...,Vible,0,1698097013000,0,Michael,True,13,QAUE7s4,False,Dadzie,https://assets.socialverseapp.com/profile/afro...,The video presents a compelling visual narrati...,15 minutes,Philosophical Exploration,True,"[{""keyword"": ""consciousness"", ""weight"": 10}, {...",Male,Unnamed Male Speaker,2.0,NaN,45,0,transcending-singularity,https://video-cdn.socialverseapp.com/michael_5...,Transcending Singularity,20,False,afrobeezy,https://video-cdn.socialverseapp.com/michael_5...,75
3,28,False,535.0,All the best vibes!,2.0,https://assets.socialverseapp.com/categories/a...,Vible,0,1698097687000,6,Michael,True,14,7bKiXIe,False,Dadzie,https://assets.socialverseapp.com/profile/afro...,The video presents a seamless narrative explor...,15:30,Motivational/Self-help,True,"[{""keyword"": ""flow state"", ""weight"": 10}, {""ke...",male,Unknown,1.0,NaN,6,0,peak-performance,https://video-cdn.socialverseapp.com/michael_4...,Peak Performance?,71,False,afrobeezy,https://video-cdn.socialverseapp.com/michael_4...,95
4,33,False,535.0,All the best vibes!,2.0,https://assets.socialverseapp.com/categories/a...,Vible,0,1698098168000,0,Michael,True,15,BLFD9FX,False,Dadzie,https://assets.socialverseapp.com/profile/afro...,"The video opens with a male speaker, who has a...",Approximately 15 minutes,Philosophical Commentary,True,"[{""keyword"": ""existential situation"", ""weight""...",Male,Not specified,1.0,[],9,0,our-existential-situation,https://video-cdn.socialverseapp.com/michael_b...,Our Existential Situation,64,False,afrobeezy,https://video-cdn.socialverseapp.com/michael_b...,72

In [84]:
filtered_df.columns

Index(['average_rating', 'bookmarked', 'category_count',
       'category_description', 'category_id', 'category_name', 'comment_count',
       'created_at', 'exit_count', 'following', 'id', 'post_summary_genre',
       'rating_count', 'share_count', 'slug', 'title', 'upvote_count',
       'upvoted', 'view_count'],
      dtype='object')

In [56]:
print(filtered_df.isnull().sum())  # Check for missing values

average_rating                     0
bookmarked                         0
category_count                     0
category_description               0
category_id                        0
category_name                      0
comment_count                      0
created_at                         0
exit_count                         0
following                          0
id                                 0
post_summary_description           0
post_summary_estimated_duration    0
post_summary_genre                 0
post_summary_keywords              0
rating_count                       0
share_count                        0
slug                               0
title                              0
upvote_count                       0
upvoted                            0
username                           0
view_count                         0
dtype: int64

In [ ]:
filtered_df.drop(columns=['post_summary_other_person_details', 'post_summary_main_person_details_name','post_summary_main_person_details_gender'], inplace=True)
filtered_df.drop(columns=['post_summary_is_face_exist','post_summary_no_of_person_in_video'], inplace=True)
filtered_df.drop(columns=['category_image_url','picture_url','thumbnail_url','identifier','is_locked','first_name','last_name'], inplace=True)
filtered_df.drop(columns=['username'], inplace=True)

In [51]:
filtered_df['post_summary_estimated_duration'].fillna(filtered_df['post_summary_estimated_duration'].mean, inplace=True)

In [83]:
filtered_df.to_csv('cleaned_posts_summary.csv', index=False)

In [106]:
viewed_posts = pd.read_csv("viewed_posts.csv")
print(viewed_posts.isnull().sum())  # Check for missing values
viewed_posts.head()

Post ID      0
User ID      0
Viewed At    0
dtype: int64

   Post ID  User ID            Viewed At
0      631      114  2024-01-10 07:20:55
1      626      114  2024-01-10 07:21:18
2      571      114  2024-01-10 07:22:02
3      558      116  2024-01-10 12:33:47
4      551      116  2024-01-10 12:33:55

In [107]:
liked_posts = pd.read_csv("liked_posts.csv")
print(liked_posts.isnull().sum())  # Check for missing values
liked_posts.head()

Post ID     0
User ID     0
Liked At    0
dtype: int64

   Post ID  User ID             Liked At
0       26        9  2023-10-24 19:28:41
1       33        9  2023-10-26 09:08:32
2       36        1  2023-10-28 09:08:35
3       36       16  2023-10-28 09:15:57
4       52        9  2023-10-30 15:48:46

In [108]:
rated_posts = pd.read_csv("rated_posts.csv")
print(rated_posts.isnull().sum())  # Check for missing values
rated_posts.head()

Post ID           0
User ID           0
Rating Percent    0
Rated At          0
dtype: int64

   Post ID  User ID  Rating Percent             Rated At
0      516        1              64  2024-01-11 12:45:41
1      160        1              62  2024-01-11 12:47:15
2       19        1              20  2024-01-11 12:47:28
3      148        1             100  2024-01-11 12:49:35
4      513        1              63  2024-01-11 12:50:58

In [109]:
inspired_posts = pd.read_csv("inspired_posts.csv")
print(inspired_posts.isnull().sum())  # Check for missing values
inspired_posts.head()

Post ID        0
User ID        0
Inspired At    0
dtype: int64

   Post ID  User ID          Inspired At
0      588        1  2023-12-31 09:06:27
1      152        1  2023-12-31 09:07:32
2      415        1  2023-12-31 09:10:09
3      558        1  2023-12-31 09:11:23
4      549        1  2023-12-31 09:11:28

In [97]:
users_data = pd.read_csv("users_data.csv")
print(users_data.isnull().sum())  # Check for missing values

User ID               0
First Name            0
Last Name             0
Username              0
Email                 0
Role                  0
Profile URL           0
Bio                1254
Website URL        1268
Instagram URL      1270
YouTube URL        1273
TikTok URL         1274
Is Verified           0
Referral Code       882
Has Wallet            0
Last Login          290
Share Count           0
Post Count            0
Following Count       0
Follower Count        0
Is Online             0
Latitude           1277
Longitude          1277
dtype: int64

In [98]:
users_data.drop( columns = ['Bio','Website URL','Instagram URL','YouTube URL','TikTok URL','Referral Code','Last Login','Latitude','Longitude'], inplace = True)

In [105]:
print(users_data.isnull().sum())  # Check for missing values
users_data.head()

User ID            0
Username           0
Role               0
Share Count        0
Post Count         0
Following Count    0
Follower Count     0
dtype: int64

,User ID,Username,Role,Share Count,Post Count,Following Count,Follower Count
0,1,afrobeezy,A,0,57,8,20
1,2,doey,U,0,0,0,0
2,3,doeyy,U,0,0,0,0
3,4,doeyyy,U,0,0,0,0
4,5,kinha,A,0,947,17,47

In [103]:
users_data.drop( columns = ['First Name','Last Name','Email','Profile URL','Is Verified','Has Wallet','Is Online'], inplace = True)

In [110]:
users_data.to_csv('cleaned_users_data.csv', index=False)

In [118]:
new_df = pd.read_csv("cleaned_posts_summary.csv")
print(new_df.isnull().sum())  # Check for missing values
new_df.head()

average_rating          0
bookmarked              0
category_count          0
category_description    0
category_id             0
category_name           0
comment_count           0
created_at              0
exit_count              0
following               0
id                      0
post_summary_genre      0
rating_count            0
share_count             0
slug                    0
title                   0
upvote_count            0
upvoted                 0
view_count              0
dtype: int64

,average_rating,bookmarked,category_count,category_description,category_id,category_name,comment_count,created_at,exit_count,following,id,post_summary_genre,rating_count,share_count,slug,title,upvote_count,upvoted,view_count
0,36,False,535.0,All the best vibes!,2.0,Vible,0,1698088807000,0,True,11,Educational/Inspirational,7,8,recipe-for-a-flow-state,Recipe for a flow state,45,True,64
1,0,False,535.0,All the best vibes!,2.0,Vible,0,1698096725000,0,True,12,Animation/Emotional Narrative,0,0,why-fit-in,Why fit in..?,42,False,54
2,8,False,535.0,All the best vibes!,2.0,Vible,0,1698097013000,0,True,13,Philosophical Exploration,45,0,transcending-singularity,Transcending Singularity,20,False,75
3,28,False,535.0,All the best vibes!,2.0,Vible,0,1698097687000,6,True,14,Motivational/Self-help,6,0,peak-performance,Peak Performance?,71,False,95
4,33,False,535.0,All the best vibes!,2.0,Vible,0,1698098168000,0,True,15,Philosophical Commentary,9,0,our-existential-situation,Our Existential Situation,64,False,72

In [125]:
new_df['post_summary_description'] = filtered_df['post_summary_description']

In [128]:
print(new_df.isnull().sum())  # Check for missing values
new_df.head()

average_rating              0
bookmarked                  0
category_count              0
category_description        0
category_id                 0
category_name               0
comment_count               0
created_at                  0
exit_count                  0
following                   0
id                          0
post_summary_genre          0
rating_count                0
share_count                 0
slug                        0
title                       0
upvote_count                0
upvoted                     0
view_count                  0
post_summary_keywords       0
post_summary_description    0
dtype: int64

,average_rating,bookmarked,category_count,category_description,category_id,category_name,comment_count,created_at,exit_count,following,id,post_summary_genre,rating_count,share_count,slug,title,upvote_count,upvoted,view_count,post_summary_keywords,post_summary_description
0,36,False,535.0,All the best vibes!,2.0,Vible,0,1698088807000,0,True,11,Educational/Inspirational,7,8,recipe-for-a-flow-state,Recipe for a flow state,45,True,64,"[{""keyword"": ""flow state"", ""weight"": 10}, {""ke...",The video unfolds as a dynamic exploration of ...
1,0,False,535.0,All the best vibes!,2.0,Vible,0,1698096725000,0,True,12,Animation/Emotional Narrative,0,0,why-fit-in,Why fit in..?,42,False,54,"[{""keyword"": ""individuality"", ""weight"": 10}, {...",The video is structured as an emotional and in...
2,8,False,535.0,All the best vibes!,2.0,Vible,0,1698097013000,0,True,13,Philosophical Exploration,45,0,transcending-singularity,Transcending Singularity,20,False,75,"[{""keyword"": ""consciousness"", ""weight"": 10}, {...",The video presents a compelling visual narrati...
3,28,False,535.0,All the best vibes!,2.0,Vible,0,1698097687000,6,True,14,Motivational/Self-help,6,0,peak-performance,Peak Performance?,71,False,95,"[{""keyword"": ""flow state"", ""weight"": 10}, {""ke...",The video presents a seamless narrative explor...
4,33,False,535.0,All the best vibes!,2.0,Vible,0,1698098168000,0,True,15,Philosophical Commentary,9,0,our-existential-situation,Our Existential Situation,64,False,72,"[{""keyword"": ""existential situation"", ""weight""...","The video opens with a male speaker, who has a..."

In [127]:
new_df['post_summary_description'].fillna('not available', inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19128\1885973922.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_df['post_summary_description'].fillna('not available', inplace=True)

In [129]:
new_df.to_csv('new_df.csv', index=False)

In [130]:
viewed_posts = pd.read_csv('viewed_posts.csv')
liked_posts = pd.read_csv('liked_posts.csv')
rated_posts = pd.read_csv('rated_posts.csv')
inspired_posts = pd.read_csv('inspired_posts.csv')
users_data = pd.read_csv('cleaned_users_data.csv')
posts_summary = pd.read_csv('cleaned_posts_summary.csv')

In [134]:
viewed_posts.head()

   Post ID  User ID            Viewed At
0      631      114  2024-01-10 07:20:55
1      626      114  2024-01-10 07:21:18
2      571      114  2024-01-10 07:22:02
3      558      116  2024-01-10 12:33:47
4      551      116  2024-01-10 12:33:55

In [147]:
posts_summary.head()

,average_rating,bookmarked,category_count,category_description,category_id,category_name,comment_count,created_at,exit_count,following,Post ID,post_summary_genre,rating_count,share_count,slug,title,upvote_count,upvoted,view_count,post_summary_keywords,post_summary_description
0,36,False,535.0,All the best vibes!,2,Vible,0,1698088807000,0,True,11,Educational/Inspirational,7,8,recipe-for-a-flow-state,Recipe for a flow state,45,True,64,"[{""keyword"": ""flow state"", ""weight"": 10}, {""ke...",The video unfolds as a dynamic exploration of ...
1,0,False,535.0,All the best vibes!,2,Vible,0,1698096725000,0,True,12,Animation/Emotional Narrative,0,0,why-fit-in,Why fit in..?,42,False,54,"[{""keyword"": ""individuality"", ""weight"": 10}, {...",The video is structured as an emotional and in...
2,8,False,535.0,All the best vibes!,2,Vible,0,1698097013000,0,True,13,Philosophical Exploration,45,0,transcending-singularity,Transcending Singularity,20,False,75,"[{""keyword"": ""consciousness"", ""weight"": 10}, {...",The video presents a compelling visual narrati...
3,28,False,535.0,All the best vibes!,2,Vible,0,1698097687000,6,True,14,Motivational/Self-help,6,0,peak-performance,Peak Performance?,71,False,95,"[{""keyword"": ""flow state"", ""weight"": 10}, {""ke...",The video presents a seamless narrative explor...
4,33,False,535.0,All the best vibes!,2,Vible,0,1698098168000,0,True,15,Philosophical Commentary,9,0,our-existential-situation,Our Existential Situation,64,False,72,"[{""keyword"": ""existential situation"", ""weight""...","The video opens with a male speaker, who has a..."

In [146]:
posts_summary['category_id'] = pd.to_numeric(posts_summary['category_id'], errors='coerce').fillna(0).astype(int)

In [148]:
posts_summary.to_csv('cleaned_summary_posts.csv', index=False)